spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks
  generic-properties:
    properties:
      historyTimeToLive: P1D

kafka:
  bootstrap-address: localhost:9092
  group-id: someGroupId
  trusted-packages: org.camunda.bpm.demo.dto